include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    cancel_subscriptions: true
    directives_ordering: true
    prefer_const_constructors: true
    prefer_final_locals: true
    prefer_null_aware_operators: true
    sort_pub_dependencies: true
    type_annotate_public_apis: true
    use_super_parameters: true
