name: licenses
description: YaruMasterDetailPage example
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  handy_window: ^0.2.1
  integration_test:
    sdk: flutter
  intl: ^0.17.0
  meta: ^1.8.0
  provider: ^6.0.5
  safe_change_notifier: ^0.2.0
  yaru: ^0.5.0
  yaru_icons: ^1.0.2
  yaru_widgets: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
